## Unknown Dataset

In [2]:
serverpath = "https://needtoknow.cz"
document = "/~profesor/data/jh-simple-dataset.csv"

In [3]:
import getpass
server = getpass.getpass()
serverpath = f"https://{server}.cz"

 ········


In [4]:
fullurl = serverpath + document

In [5]:
import pandas as pd

df = pd.read_csv(fullurl, na_values=["NA", "?"])
display(df)

id job area   income     aspect  subscriptions  dist_healthy  \
0        1  vv    c  50876.0  13.100000              1      9.017895   
1        2  kd    c  60369.0  18.625000              2      7.766643   
2        3  pe    c  55126.0  34.766667              1      3.632069   
3        4  11    c  51690.0  15.808333              1      5.372942   
4        5  kl    d  28347.0  40.941667              3      3.822477   
...    ...  ..  ...      ...        ...            ...           ...   
1995  1996  vv    c  51017.0  38.233333              1      5.454545   
1996  1997  kl    d  26576.0  33.358333              2      3.632069   
1997  1998  kl    d  28595.0  39.425000              3      7.168218   
1998  1999  qp    c  67949.0   5.733333              0      8.936292   
1999  2000  pe    c  61467.0  16.891667              0      4.312097   

      save_rate  dist_unhealthy  age  pop_dense  retail_dense     crime  \
0            35       11.738935   49   0.885827      0.492126  0.071100   
1            59        6.805396   51   0.874016      0.342520  0.400809   
2             6       13.671772   44   0.944882      0.724409  0.207723   
3            16        4.333286   50   0.889764      0.444882  0.361216   
4            20        5.967121   38   0.744094      0.661417  0.068033   
...         ...             ...  ...        ...           ...       ...   
1995         34       14.013489   41   0.881890      0.744094  0.104838   
1996         20        8.380497   38   0.944882      0.877953  0.063851   
1997         99        4.626950   36   0.759843      0.744094  0.098703   
1998         26        3.281439   46   0.909449      0.598425  0.117803   
1999          8        9.405648   48   0.925197      0.539370  0.451973   

     product  
0          b  
1          c  
2          b  
3          b  
4          a  
...      ...  
1995       b  
1996       a  
1997       f  
1998       c  
1999       c  

[2000 rows x 14 columns]

In [6]:
dummies = pd.get_dummies(df["job"], prefix="job")
print(dummies.shape)
dummies

(2000, 33)


job_11  job_al  job_am  job_ax  job_bf  job_by  job_cv  job_de  job_dz  \
0          0       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          0       0       0       0       0       0       0       0       0   
3          1       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1995       0       0       0       0       0       0       0       0       0   
1996       0       0       0       0       0       0       0       0       0   
1997       0       0       0       0       0       0       0       0       0   
1998       0       0       0       0       0       0       0       0       0   
1999       0       0       0       0       0       0       0       0       0   

      job_e2  ...  job_pe  job_po  job_pq  job_pz  job_qp  job_qw  job_rn  \
0          0  ...       0       0       0       0       0       0       0   
1          0  ...       0       0       0       0       0       0       0   
2          0  ...       1       0       0       0       0       0       0   
3          0  ...       0       0       0       0       0       0       0   
4          0  ...       0       0       0       0       0       0       0   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
1995       0  ...       0       0       0       0       0       0       0   
1996       0  ...       0       0       0       0       0       0       0   
1997       0  ...       0       0       0       0       0       0       0   
1998       0  ...       0       0       0       0       1       0       0   
1999       0  ...       1       0       0       0       0       0       0   

      job_sa  job_vv  job_zz  
0          0       1       0  
1          0       0       0  
2          0       0       0  
3          0       0       0  
4          0       0       0  
...      ...     ...     ...  
1995       0       1       0  
1996       0       0       0  
1997       0       0       0  
1998       0       0       0  
1999       0       0       0  

[2000 rows x 33 columns]

In [8]:
df2 = pd.concat([df, dummies], axis=1)
df2.drop("job", axis=1, inplace=True)
df2

id area   income     aspect  subscriptions  dist_healthy  save_rate  \
0        1    c  50876.0  13.100000              1      9.017895         35   
1        2    c  60369.0  18.625000              2      7.766643         59   
2        3    c  55126.0  34.766667              1      3.632069          6   
3        4    c  51690.0  15.808333              1      5.372942         16   
4        5    d  28347.0  40.941667              3      3.822477         20   
...    ...  ...      ...        ...            ...           ...        ...   
1995  1996    c  51017.0  38.233333              1      5.454545         34   
1996  1997    d  26576.0  33.358333              2      3.632069         20   
1997  1998    d  28595.0  39.425000              3      7.168218         99   
1998  1999    c  67949.0   5.733333              0      8.936292         26   
1999  2000    c  61467.0  16.891667              0      4.312097          8   

      dist_unhealthy  age  pop_dense  ...  job_pe  job_po job_pq  job_pz  \
0          11.738935   49   0.885827  ...       0       0      0       0   
1           6.805396   51   0.874016  ...       0       0      0       0   
2          13.671772   44   0.944882  ...       1       0      0       0   
3           4.333286   50   0.889764  ...       0       0      0       0   
4           5.967121   38   0.744094  ...       0       0      0       0   
...              ...  ...        ...  ...     ...     ...    ...     ...   
1995       14.013489   41   0.881890  ...       0       0      0       0   
1996        8.380497   38   0.944882  ...       0       0      0       0   
1997        4.626950   36   0.759843  ...       0       0      0       0   
1998        3.281439   46   0.909449  ...       0       0      0       0   
1999        9.405648   48   0.925197  ...       1       0      0       0   

      job_qp  job_qw  job_rn  job_sa  job_vv  job_zz  
0          0       0       0       0       1       0  
1          0       0       0       0       0       0  
2          0       0       0       0       0       0  
3          0       0       0       0       0       0  
4          0       0       0       0       0       0  
...      ...     ...     ...     ...     ...     ...  
1995       0       0       0       0       1       0  
1996       0       0       0       0       0       0  
1997       0       0       0       0       0       0  
1998       1       0       0       0       0       0  
1999       0       0       0       0       0       0  

[2000 rows x 46 columns]

In [10]:
df3 = pd.concat([df2, pd.get_dummies(df2["area"], prefix="area")], axis=1)
df3.drop("area", axis=1, inplace=True)
df3

id   income     aspect  subscriptions  dist_healthy  save_rate  \
0        1  50876.0  13.100000              1      9.017895         35   
1        2  60369.0  18.625000              2      7.766643         59   
2        3  55126.0  34.766667              1      3.632069          6   
3        4  51690.0  15.808333              1      5.372942         16   
4        5  28347.0  40.941667              3      3.822477         20   
...    ...      ...        ...            ...           ...        ...   
1995  1996  51017.0  38.233333              1      5.454545         34   
1996  1997  26576.0  33.358333              2      3.632069         20   
1997  1998  28595.0  39.425000              3      7.168218         99   
1998  1999  67949.0   5.733333              0      8.936292         26   
1999  2000  61467.0  16.891667              0      4.312097          8   

      dist_unhealthy  age  pop_dense  retail_dense  ...  job_qp job_qw  \
0          11.738935   49   0.885827      0.492126  ...       0      0   
1           6.805396   51   0.874016      0.342520  ...       0      0   
2          13.671772   44   0.944882      0.724409  ...       0      0   
3           4.333286   50   0.889764      0.444882  ...       0      0   
4           5.967121   38   0.744094      0.661417  ...       0      0   
...              ...  ...        ...           ...  ...     ...    ...   
1995       14.013489   41   0.881890      0.744094  ...       0      0   
1996        8.380497   38   0.944882      0.877953  ...       0      0   
1997        4.626950   36   0.759843      0.744094  ...       0      0   
1998        3.281439   46   0.909449      0.598425  ...       1      0   
1999        9.405648   48   0.925197      0.539370  ...       0      0   

      job_rn  job_sa  job_vv  job_zz  area_a  area_b  area_c  area_d  
0          0       0       1       0       0       0       1       0  
1          0       0       0       0       0       0       1       0  
2          0       0       0       0       0       0       1       0  
3          0       0       0       0       0       0       1       0  
4          0       0       0       0       0       0       0       1  
...      ...     ...     ...     ...     ...     ...     ...     ...  
1995       0       0       1       0       0       0       1       0  
1996       0       0       0       0       0       0       0       1  
1997       0       0       0       0       0       0       0       1  
1998       0       0       0       0       0       0       1       0  
1999       0       0       0       0       0       0       1       0  

[2000 rows x 49 columns]

In [12]:
df3['income'].isnull().any()

True

In [13]:
med = df3["income"].median()
df3["income"] = df3["income"].fillna(med)
df3

id   income     aspect  subscriptions  dist_healthy  save_rate  \
0        1  50876.0  13.100000              1      9.017895         35   
1        2  60369.0  18.625000              2      7.766643         59   
2        3  55126.0  34.766667              1      3.632069          6   
3        4  51690.0  15.808333              1      5.372942         16   
4        5  28347.0  40.941667              3      3.822477         20   
...    ...      ...        ...            ...           ...        ...   
1995  1996  51017.0  38.233333              1      5.454545         34   
1996  1997  26576.0  33.358333              2      3.632069         20   
1997  1998  28595.0  39.425000              3      7.168218         99   
1998  1999  67949.0   5.733333              0      8.936292         26   
1999  2000  61467.0  16.891667              0      4.312097          8   

      dist_unhealthy  age  pop_dense  retail_dense  ...  job_qp job_qw  \
0          11.738935   49   0.885827      0.492126  ...       0      0   
1           6.805396   51   0.874016      0.342520  ...       0      0   
2          13.671772   44   0.944882      0.724409  ...       0      0   
3           4.333286   50   0.889764      0.444882  ...       0      0   
4           5.967121   38   0.744094      0.661417  ...       0      0   
...              ...  ...        ...           ...  ...     ...    ...   
1995       14.013489   41   0.881890      0.744094  ...       0      0   
1996        8.380497   38   0.944882      0.877953  ...       0      0   
1997        4.626950   36   0.759843      0.744094  ...       0      0   
1998        3.281439   46   0.909449      0.598425  ...       1      0   
1999        9.405648   48   0.925197      0.539370  ...       0      0   

      job_rn  job_sa  job_vv  job_zz  area_a  area_b  area_c  area_d  
0          0       0       1       0       0       0       1       0  
1          0       0       0       0       0       0       1       0  
2          0       0       0       0       0       0       1       0  
3          0       0       0       0       0       0       1       0  
4          0       0       0       0       0       0       0       1  
...      ...     ...     ...     ...     ...     ...     ...     ...  
1995       0       0       1       0       0       0       1       0  
1996       0       0       0       0       0       0       0       1  
1997       0       0       0       0       0       0       0       1  
1998       0       0       0       0       0       0       1       0  
1999       0       0       0       0       0       0       1       0  

[2000 rows x 49 columns]

In [15]:
x_columns = df3.columns.drop(["product", "id"])
x_columns

Index(['income', 'aspect', 'subscriptions', 'dist_healthy', 'save_rate',
       'dist_unhealthy', 'age', 'pop_dense', 'retail_dense', 'crime', 'job_11',
       'job_al', 'job_am', 'job_ax', 'job_bf', 'job_by', 'job_cv', 'job_de',
       'job_dz', 'job_e2', 'job_f8', 'job_gj', 'job_gv', 'job_kd', 'job_ke',
       'job_kl', 'job_kp', 'job_ks', 'job_kw', 'job_mm', 'job_nb', 'job_nn',
       'job_ob', 'job_pe', 'job_po', 'job_pq', 'job_pz', 'job_qp', 'job_qw',
       'job_rn', 'job_sa', 'job_vv', 'job_zz', 'area_a', 'area_b', 'area_c',
       'area_d'],
      dtype='object')

In [24]:
from sklearn import preprocessing

# Convert to numpy - Classification
x_columns = df3.columns.drop(["product", "id"])

print(x_columns)

x = df3[x_columns].values
le = preprocessing.LabelEncoder()
y = le.fit_transform(df3["product"])
products = le.classes_
y = dummies.values

Index(['income', 'aspect', 'subscriptions', 'dist_healthy', 'save_rate',
       'dist_unhealthy', 'age', 'pop_dense', 'retail_dense', 'crime', 'job_11',
       'job_al', 'job_am', 'job_ax', 'job_bf', 'job_by', 'job_cv', 'job_de',
       'job_dz', 'job_e2', 'job_f8', 'job_gj', 'job_gv', 'job_kd', 'job_ke',
       'job_kl', 'job_kp', 'job_ks', 'job_kw', 'job_mm', 'job_nb', 'job_nn',
       'job_ob', 'job_pe', 'job_po', 'job_pq', 'job_pz', 'job_qp', 'job_qw',
       'job_rn', 'job_sa', 'job_vv', 'job_zz', 'area_a', 'area_b', 'area_c',
       'area_d'],
      dtype='object')


In [30]:
len(dummies.columns)

33

In [25]:
x

array([[5.08760000e+04, 1.31000000e+01, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [6.03690000e+04, 1.86250000e+01, 2.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [5.51260000e+04, 3.47666667e+01, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [2.85950000e+04, 3.94250000e+01, 3.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [6.79490000e+04, 5.73333333e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [6.14670000e+04, 1.68916667e+01, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [26]:
y

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [49]:
import torch
import torch.nn as nn

x = torch.tensor(x, device="cpu", dtype=torch.float32)
y = torch.tensor(y, device="cpu", dtype=torch.long)

model = nn.Sequential(
    nn.Linear(x.shape[1], 50),
    nn.ReLU(),
    nn.Linear(50, 25),
    nn.ReLU(),
    nn.Linear(25, len(species)),
    nn.LogSoftmax(dim=1),
)

https://pytorch.org/docs/stable/generated/torch.nn.Linear.html

https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html

https://pytorch.org/docs/stable/generated/torch.nn.LogSoftmax.html

In [50]:
# PyTorch 2.0 Model Compile (improved performance)
model = torch.compile(model,backend="aot_eager").to(device)

criterion = nn.CrossEntropyLoss()  # cross entropy loss

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

model.train()
for epoch in range(1000):
    optimizer.zero_grad()
    out = model(x)
    # Note: CrossEntropyLoss combines nn.LogSoftmax() and nn.NLLLoss() so don't use Softmax in the model
    loss = criterion(out, y)
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, loss: {loss.item()}")

Epoch 0, loss: 1.182706356048584
Epoch 100, loss: 0.05040304362773895
Epoch 200, loss: 0.04457595571875572
Epoch 300, loss: 0.040220893919467926
Epoch 400, loss: 0.03675726801156998
Epoch 500, loss: 0.03613399341702461
Epoch 600, loss: 0.03427649289369583
Epoch 700, loss: 0.03405502811074257
Epoch 800, loss: 0.033910878002643585
Epoch 900, loss: 0.03368908911943436


In [51]:
model.eval()
pred = model(x)
print(f"Shape: {pred.shape}")
print(pred[0:10])

Shape: torch.Size([150, 3])
tensor([[-4.6492e-06, -1.2289e+01, -4.4276e+01],
        [-1.6570e-05, -1.1011e+01, -4.0573e+01],
        [-8.9407e-06, -1.1626e+01, -4.1806e+01],
        [-1.9789e-05, -1.0828e+01, -3.9910e+01],
        [-3.8147e-06, -1.2462e+01, -4.4619e+01],
        [-9.2983e-06, -1.1589e+01, -4.4032e+01],
        [-1.0490e-05, -1.1462e+01, -4.1586e+01],
        [-7.9870e-06, -1.1731e+01, -4.2839e+01],
        [-2.7179e-05, -1.0513e+01, -3.8618e+01],
        [-1.2517e-05, -1.1293e+01, -4.1394e+01]], grad_fn=<SliceBackward0>)


In [52]:
print(pred[0:10].cpu().detach().numpy())

[[-4.64915138e-06 -1.22889528e+01 -4.42761536e+01]
 [-1.65699548e-05 -1.10109434e+01 -4.05728912e+01]
 [-8.94065670e-06 -1.16256256e+01 -4.18063736e+01]
 [-1.97885456e-05 -1.08280735e+01 -3.99100571e+01]
 [-3.81468999e-06 -1.24619789e+01 -4.46187973e+01]
 [-9.29828093e-06 -1.15892076e+01 -4.40320663e+01]
 [-1.04903629e-05 -1.14624834e+01 -4.15859184e+01]
 [-7.98699057e-06 -1.17310820e+01 -4.28389969e+01]
 [-2.71793488e-05 -1.05131416e+01 -3.86175652e+01]
 [-1.25168972e-05 -1.12926235e+01 -4.13938675e+01]]


In [53]:
_, predict_classes = torch.max(pred, 1)
print(f"Predictions: {predict_classes}")
print(f"Expected: {y}")

Predictions: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2])
Expected: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [56]:
print(species[predict_classes])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor